<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TCP</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TCP.Tests" />
    <InternalsVisibleTo Include="TCP.Explorer" />
    <InternalsVisibleTo Include="TCP.Explorer.Browser" />
  </ItemGroup>
</Project>
