import { q } from './types';

export const automation = [
  q('automation-001', '6.1', 'Why can automation reduce errors when applying the same change to many devices?', "Apply and validate consistent intent through a reviewed workflow", ["Automation eliminates compatibility checks between platforms", "A template is safe because the same commands run everywhere", "Successful submission guarantees every intended result"], 'Automation improves repeatability, but a wrong template can spread errors quickly. Validate inputs, device compatibility, results, and rollback rather than assuming automation makes the change inherently correct.'),
  q('automation-002', '6.1', 'An automation job reports success after sending commands. What should happen before declaring the network change successful?', 'Verify intended configuration and operational behavior', ["Treat command submission as proof of operational success", "Verify only the count of submitted commands", "Suppress monitoring because automation has replaced it"], 'Submission success is different from the intended network outcome. Read back state and perform relevant traffic checks, with safeguards against unintended changes.'),
  q('automation-003', '6.2', 'What distinguishes controller-based management from individually configuring each device?', "Centralized intent and policy via device interfaces", ["The controller must carry every forwarded client packet", "Traditional device management cannot use scripts", "The controller removes every device's forwarding function"], 'Controller-based management centralizes coordination and policy. Devices can still forward traffic locally, and traditional management can also be automated without that same controller architecture.'),
  q('automation-004', '6.2', 'A controller becomes unreachable while switches retain installed forwarding entries. Which statement is most accurate?', "Forwarding may continue; control operations depend on the design", ["Every controller-based design immediately stops all forwarding", "Existing entries guarantee all future policy changes still succeed", "Controller loss affects no operation in any architecture"], 'Control-plane and data-plane separation can let existing forwarding continue. Failure behavior is architecture-specific, so do not assume universal availability or universal shutdown.'),
  q('automation-005', '6.3', 'Which activity belongs primarily to the data plane?', "Forward using installed state", ["Calculating routes after a topology change", "Exchanging routing protocol updates", "Changing the interface configuration through an API"], 'The data plane moves packets. Control-plane functions determine the forwarding information, and management-plane operations configure and observe the system.', '', 'Understand'),
  q('automation-006', '6.3', 'Which activity belongs primarily to the control plane?', 'Exchanging routing information and computing routes', ["Forwarding packets from installed entries", "Queuing packets on an egress interface", "Classifying traffic with an installed forwarding policy"], 'Routing exchanges and path computation determine where traffic should go. The data plane applies the resulting forwarding decisions.', '', 'Understand'),
  q('automation-007', '6.3', 'An orchestration application asks a network controller to create policy. Which interface direction is this commonly called?', 'Northbound', ["Southbound toward a managed device", "A device's local data-plane interface", "An underlay tunnel between fabric nodes"], 'Northbound APIs connect controller capabilities to consuming applications. Southbound interfaces connect the controller toward managed infrastructure.'),
  q('automation-008', '6.3', 'A controller programs network devices through a device-facing interface. Which direction is this?', 'Southbound', ["Northbound toward a consuming application", "A controller-to-controller business application interface", "The client's overlay data path"], 'Southbound interfaces connect controller logic to devices or underlying infrastructure. They are a direction in the architecture, not one mandated universal protocol.'),
  q('automation-009', '6.3', 'Which description correctly relates an overlay and underlay?', "Logical overlay connectivity over underlay transport", ["The overlay supplies physical transport and the underlay supplies tenant segmentation", "An overlay eliminates dependency on underlay reachability", "Overlay and underlay must use identical addressing and routing tables"], 'An underlay supplies the transport path, while an overlay builds logical networks over it, often through encapsulation. Underlay reachability failures can therefore break overlay connectivity.'),
  q('automation-010', '6.4', 'A system forecasts link congestion from historical counters. Which AI use is this closest to?', 'Predictive analysis', ["Generative content creation", "A fixed threshold alarm with no forecasting", "Manual counter collection without prediction"], 'Predicting a future condition from observations is predictive analysis. Generative AI creates content; both require appropriate data quality and validation.'),
  q('automation-011', '6.4', 'An assistant drafts a router configuration from a written requirement. Which AI use is this closest to?', 'Generative AI', ["Predictive forecasting of future traffic", "A fixed forwarding-table lookup", "An anomaly score without generated content"], 'Producing new text or configuration is generative use. The generated result still needs technical review and a test against the requirement before application.'),
  q('automation-012', '6.4', 'A machine-learning anomaly detector labels new office traffic suspicious. What should an operator do?', "Investigate evidence, false positives, and baseline changes", ["Treat the prediction as proof of compromise", "Ignore changed traffic baselines because training fixes them permanently", "Suppress the supporting observations after the alert"], 'Models infer patterns and can be wrong, especially when traffic changes. An alert supports investigation; it is not automatically proof of an incident.', '', 'Troubleshoot'),
  q("automation-crud-contract", "6.5", "Which method sequence matches the four operations under this API contract?", "GET, POST, PUT, DELETE", ["GET, PUT, POST, DELETE", "POST, GET, PATCH, DELETE", "GET, POST, DELETE, PUT"], "HTTP defines method semantics; API contracts determine the supported resource operations. Here GET reads, POST creates in a collection, PUT replaces the complete representation, and DELETE removes the specified resource. PATCH can apply a partial update when the API supports it; it is not the full replacement in this contract.", "Illustrative API contract\nCollection: /vlans; resource: /vlans/20\nUse conventional read/create/replace/delete methods.\nPUT replaces the complete resource representation; PATCH changes supplied fields only.\nRequested operations in order: read, create, replace, remove.", "Apply"),
  q('automation-014', '6.5', 'Under this API contract, which request changes only one supplied field?', 'PATCH /interfaces/Gi0%2F1 with {"enabled":false}', ["GET /interfaces/Gi0%2F1 with no body", "DELETE /interfaces/Gi0%2F1", "PUT /interfaces/Gi0%2F1 with only the enabled field under a replacement contract"], 'The supplied contract defines PATCH as partial update. GET reads and DELETE removes; PUT commonly replaces a resource, though actual API behavior must always be checked.', 'Contract: PATCH updates supplied fields only\nGoal: disable one interface without replacing its other properties'),
  q('automation-015', '6.5', 'A REST request uses a bearer token. Which practice protects that credential in transit?', "Validated HTTPS plus secret handling", ["Send the token over HTTP because its format encrypts it", "Place the token in a publicly accessible request log", "Trust any TLS endpoint certificate without validation"], 'A bearer token grants access to its holder and does not itself encrypt the connection. TLS protects transport and endpoint identity; careful secret handling reduces disclosure.'),
  q('automation-016', '6.5', 'An API returns this response. What can you conclude?', "The request succeeded; the interface is operationally down", ["HTTP 200 proves the interface is forwarding", "Administrative enabled state overrides observed link state", "Operational down means the JSON response is invalid"], 'HTTP success describes the request outcome. Administrative enabled state and operational link state are separate; verify link conditions and traffic rather than interpreting 200 as network health.', 'HTTP 200 OK\n{"enabled":true,"operStatus":"down"}', 'Troubleshoot'),
  q("automation-ansible-task", "6.6", "What configuration does this Ansible task request on each inventory host in lab_switches?", "Set Gi0/1 description to StudyLab using the IOS configuration module", ["Configure the description on the controller only, not the inventory hosts", "Delete Gi0/1 because parents names the interface to remove", "Guarantee identical results on every vendor OS without a supported connection"], "The hosts pattern selects inventory devices. parents locates the IOS configuration section and lines supplies its intended configuration. The task requires the cisco.ios collection, supported network connection, credentials, and correct device selection. ios_config compares supported lines against running configuration; abbreviated commands or inappropriate tasks can undermine repeat-run behavior. Review and verify results.", "Illustrative playbook task excerpt; connection and credentials configured separately\n- name: Label lab uplinks\n  hosts: lab_switches\n  gather_facts: false\n  tasks:\n    - name: Set interface description\n      cisco.ios.ios_config:\n        parents: interface GigabitEthernet0/1\n        lines:\n          - description StudyLab", "Apply"),
  q("automation-terraform-plan", "6.6", "What does this Terraform plan establish before application?", "It proposes one in-place update; it has not applied the change", ["It has already updated the device and verified traffic forwarding", "It proposes destroying and recreating one resource", "It proves state and the saved plan contain no sensitive data"], "The ~ symbol denotes an in-place update, with no resources added or destroyed in this plan. A plan previews proposed provider actions; apply performs changes and operational checks are still needed. State maps declared resources to managed objects and can contain secrets. Provider capabilities and refreshed state determine the plan, so do not infer universal network-device support.", "Illustrative provider plan excerpt; resource type is a placeholder\n  # example_interface.uplink will be updated in-place\n  ~ resource \"example_interface\" \"uplink\" {\n      description = \"Old\" -> \"StudyLab\"\n    }\nPlan: 0 to add, 1 to change, 0 to destroy.", "Apply"),
  q('automation-019', '6.7', 'Which interpretation of this JSON is correct?', "interfaces: array; first item: object; enabled: Boolean; vlan: number", ["interfaces is an object; enabled is a string; vlan is Boolean", "interfaces is an array; enabled is a string; vlan is numeric", "interfaces is an array; enabled is Boolean; vlan is a string"], 'Brackets delimit an array and braces an object. true is Boolean, 20 is numeric, and the quoted interface name is a string.', '{"interfaces":[{"name":"Gi0/1","enabled":true,"vlan":20}]}'),
  q('automation-020', '6.7', 'Which value is valid JSON for an administratively disabled interface?', '{"enabled":false}', ["{enabled:false}", "{\"enabled\":False}", "{\"enabled\":false,}"], 'JSON requires double-quoted object keys, lowercase Boolean literals, and no trailing comma. A quoted "false" would be a string rather than the Boolean false.')
];
