import { q } from './types';

export const automation = [
  q('6.1', 'Why can automation reduce errors when applying the same change to many devices?', 'A reviewed repeatable workflow can apply and validate consistent intent', ['It removes the need for any review or testing', 'It guarantees that a mistaken template cannot spread', 'It makes every device support identical commands'], 'Automation improves repeatability, but a wrong template can spread errors quickly. Validate inputs, device compatibility, results, and rollback rather than assuming automation makes the change inherently correct.'),
  q('6.1', 'An automation job reports success after sending commands. What should happen before declaring the network change successful?', 'Verify intended configuration and operational behavior', ['Assume command submission proves end-to-end connectivity', 'Disable monitoring because automation replaced it', 'Count only how many commands were sent'], 'Submission success is different from the intended network outcome. Read back state and perform relevant traffic checks, with safeguards against unintended changes.'),
  q('6.2', 'What distinguishes controller-based management from individually configuring each device?', 'A controller can maintain centralized intent and coordinate policy through device interfaces', ['Controllers eliminate the data plane from every device', 'A controller must physically carry every client packet', 'Individual management cannot use any scripts'], 'Controller-based management centralizes coordination and policy. Devices can still forward traffic locally, and traditional management can also be automated without that same controller architecture.'),
  q('6.2', 'A controller becomes unreachable while switches retain installed forwarding entries. Which statement is most accurate?', 'Existing forwarding may continue, but new control or management operations can be affected depending on the design', ['Every architecture must immediately stop all forwarding', 'Controllers have no relation to control or management', 'Every switch loses power when the controller fails'], 'Control-plane and data-plane separation can let existing forwarding continue. Failure behavior is architecture-specific, so do not assume universal availability or universal shutdown.'),
  q('6.3', 'Which activity belongs primarily to the data plane?', 'Forwarding a packet using installed forwarding state', ['Calculating a new routing topology', 'Editing a configuration through the management UI', 'Generating an administrator’s password policy'], 'The data plane moves packets. Control-plane functions determine the forwarding information, and management-plane operations configure and observe the system.', '', 'Understand'),
  q('6.3', 'Which activity belongs primarily to the control plane?', 'Exchanging routing information and computing routes', ['Sending a frame out an interface using an existing entry', 'Applying a physical cable label', 'Delivering electrical power to an AP'], 'Routing exchanges and path computation determine where traffic should go. The data plane applies the resulting forwarding decisions.', '', 'Understand'),
  q('6.3', 'An orchestration application asks a network controller to create policy. Which interface direction is this commonly called?', 'Northbound', ['Southbound toward a managed switch', 'An Ethernet native VLAN', 'An NTP stratum'], 'Northbound APIs connect controller capabilities to consuming applications. Southbound interfaces connect the controller toward managed infrastructure.'),
  q('6.3', 'A controller programs network devices through a device-facing interface. Which direction is this?', 'Southbound', ['Northbound toward a business application', 'IPv4 limited broadcast', 'A client DNS suffix'], 'Southbound interfaces connect controller logic to devices or underlying infrastructure. They are a direction in the architecture, not one mandated universal protocol.'),
  q('6.3', 'Which description correctly relates an overlay and underlay?', 'The overlay provides logical connectivity over an underlay that supplies transport reachability', ['The overlay replaces every physical link so no transport is needed', 'The underlay is the browser’s CSS theme', 'A fabric prohibits all logical segmentation'], 'An underlay supplies the transport path, while an overlay builds logical networks over it, often through encapsulation. Underlay reachability failures can therefore break overlay connectivity.'),
  q('6.4', 'A system forecasts link congestion from historical counters. Which AI use is this closest to?', 'Predictive analysis', ['Generating a new configuration document', 'Encrypting an SSH session', 'Electing an OSPF DR'], 'Predicting a future condition from observations is predictive analysis. Generative AI creates content; both require appropriate data quality and validation.'),
  q('6.4', 'An assistant drafts a router configuration from a written requirement. Which AI use is this closest to?', 'Generative AI', ['Only an Ethernet forwarding lookup', 'A passive fiber splice', 'A DNS authoritative zone transfer'], 'Producing new text or configuration is generative use. The generated result still needs technical review and a test against the requirement before application.'),
  q('6.4', 'A machine-learning anomaly detector labels new office traffic suspicious. What should an operator do?', 'Examine the evidence and context, including false positives and changed baselines', ['Treat every model prediction as proven malicious behavior', 'Assume machine learning cannot use historical patterns', 'Disable all logging to improve the prediction'], 'Models infer patterns and can be wrong, especially when traffic changes. An alert supports investigation; it is not automatically proof of an incident.', '', 'Troubleshoot'),
  q('6.5', 'Which HTTP method commonly reads a resource without requesting a state change?', 'GET', ['DELETE', 'POST as the general read-only default', 'PATCH'], 'GET retrieves a representation. DELETE removes a resource, PATCH updates part of one, and POST commonly creates or invokes an operation according to the API contract.'),
  q('6.5', 'Under this API contract, which request changes only one supplied field?', 'PATCH /interfaces/Gi0%2F1 with {"enabled":false}', ['GET /interfaces/Gi0%2F1 with no body', 'DELETE /interfaces as a partial update', 'PUT /interfaces with an unrelated string'], 'The supplied contract defines PATCH as partial update. GET reads and DELETE removes; PUT commonly replaces a resource, though actual API behavior must always be checked.', 'Contract: PATCH updates supplied fields only\nGoal: disable one interface without replacing its other properties'),
  q('6.5', 'A REST request uses a bearer token. Which practice protects that credential in transit?', 'Use authenticated HTTPS and handle the token as a secret', ['Put the token into a public screenshot', 'Use plain HTTP because bearer tokens encrypt themselves', 'Assume the token is safe because it is JSON'], 'A bearer token grants access to its holder and does not itself encrypt the connection. TLS protects transport and endpoint identity; careful secret handling reduces disclosure.'),
  q('6.5', 'An API returns this response. What can you conclude?', 'The resource was returned successfully, but the interface is operationally down', ['All traffic is forwarding because HTTP is 200', 'The Boolean true is invalid JSON', 'The API automatically repairs the cable on every GET'], 'HTTP success describes the request outcome. Administrative enabled state and operational link state are separate; verify link conditions and traffic rather than interpreting 200 as network health.', 'HTTP 200 OK\n{"enabled":true,"operStatus":"down"}', 'Troubleshoot'),
  q('6.6', 'Which capability is commonly associated with Ansible?', 'Applying configuration tasks through playbooks and supported device connections', ['Replacing every Ethernet frame header with JSON', 'Guaranteeing every repeated task is idempotent without design', 'Physically supplying PoE power'], 'Ansible automates tasks through playbooks and modules/connections. Idempotence depends on the chosen tasks and mechanisms, so review what repeated runs actually do.'),
  q('6.6', 'Which capability is commonly associated with Terraform?', 'Managing declared infrastructure through providers, plans, and state', ['Performing RF amplification inside an AP', 'A guarantee that state never contains sensitive information', 'Replacing DNS resolution with VLAN tags'], 'Terraform manages desired infrastructure with provider resources and state, typically showing a plan before application. State handling and provider behavior need care; they are not automatically free of secrets or change risk.'),
  q('6.7', 'Which interpretation of this JSON is correct?', 'interfaces is an array; its first item is an object; enabled is Boolean and vlan is numeric', ['interfaces is a Boolean and vlan is a string', 'The unquoted true makes the JSON invalid', 'The square brackets describe a routing prefix'], 'Brackets delimit an array and braces an object. true is Boolean, 20 is numeric, and the quoted interface name is a string.', '{"interfaces":[{"name":"Gi0/1","enabled":true,"vlan":20}]}'),
  q('6.7', 'Which value is valid JSON for an administratively disabled interface?', '{"enabled":false}', ['{enabled:false}', '{"enabled":False}', '{"enabled":false,}'], 'JSON requires double-quoted object keys, lowercase Boolean literals, and no trailing comma. A quoted "false" would be a string rather than the Boolean false.')
];
