import { q } from './types';

export const services = [
  q('4.1', 'Which Cisco IOS command creates this static inside-source mapping?', 'ip nat inside source static 10.0.0.10 203.0.113.10', ['ip nat inside source static 203.0.113.10 10.0.0.10', 'ip helper-address 203.0.113.10', 'ip route 10.0.0.10 255.255.255.255 203.0.113.10'], 'The static inside-source syntax lists inside local before inside global. Interface roles and routing also need to be correct; a route or DHCP helper does not create the translation.', 'Inside local: 10.0.0.10\nInside global: 203.0.113.10\nClosed documentation-address lab'),
  q('4.1', 'A dynamic NAT pool has two addresses and no overload. Three hosts need simultaneous distinct translations. What limitation should be expected?', 'The pool can exhaust because ordinary dynamic NAT needs an available global address per active mapping', ['The pool automatically supplies unlimited PAT ports without overload', 'All hosts must use the same inside-local address', 'DNS automatically expands the configured pool'], 'Pool-based dynamic NAT without overload is address-based. When the pool is exhausted, another required mapping cannot be allocated until an address becomes available.'),
  q('4.1', 'The translation exists but the remote application times out. What conclusion is justified?', 'NAT state exists, but routing, filtering, and the remote service still need verification', ['The server must be healthy because a translation exists', 'All return traffic is guaranteed to pass', 'The NAT table proves the DNS answer is correct'], 'NAT is only one part of delivery. Check inside/outside interfaces, path, policy, and replies; a table entry does not prove end-to-end application success.', 'tcp 203.0.113.5:40001 10.0.0.10:51500 198.51.100.20:443', 'Troubleshoot'),
  q('4.2', 'Which command makes an IOS device obtain time from this NTP server?', 'ntp server 192.0.2.10', ['ntp master 10 as the client-server address command', 'ip helper-address 192.0.2.10', 'logging host 192.0.2.10'], 'ntp server identifies a time source. ntp master makes a device offer its own time source; DHCP relay and syslog commands do not establish NTP synchronization.'),
  q('4.2', 'Why is NTP synchronization useful for troubleshooting multiple devices?', 'It makes event timestamps comparable across devices', ['It guarantees all traffic has zero latency', 'It replaces the router’s forwarding table', 'It sets every client’s VLAN membership'], 'Consistent clocks help correlate events and logs. NTP does not remove latency or configure routes and VLANs; verify actual synchronization rather than just server configuration.'),
  q('4.3', 'Which service supplies a client’s leased IP configuration, and which resolves a hostname?', 'DHCP supplies configuration; DNS resolves names', ['DNS leases addresses; DHCP resolves names', 'NTP performs both', 'ARP performs both across the Internet'], 'DHCP can supply address, mask, router, and DNS options. DNS maps names to records; ARP resolves local IPv4 next-hop MAC addresses.', '', 'Understand'),
  q('4.3', 'Access to a service by IP succeeds but access by hostname fails. Which check is most relevant next?', 'The client’s DNS server setting and the name’s DNS response', ['Replacing every physical switch first', 'Matching OSPF process IDs between all devices', 'Removing the DHCP relay even though the lease is valid'], 'The successful IP test narrows the failure toward name resolution or name-specific application behavior. Check the actual DNS answer rather than assuming IP routing is the only problem.', '', 'Troubleshoot'),
  q('4.4', 'An operations system polls interface counters and receives device traps. Which protocol is commonly involved?', 'SNMP', ['FTP', 'LACP', 'ARP'], 'SNMP provides management polling and notifications. Version 3 can support authentication and privacy; merely using SNMP does not imply encrypted management.', '', 'Understand'),
  q('4.5', 'Which syslog severity is more urgent?', 'Severity 2 is more urgent than severity 5', ['Severity 5 is more urgent because its number is larger', 'All severities have identical meaning', 'Severity is the VLAN number'], 'Syslog severity runs from 0 emergency to 7 debugging; lower numbers indicate greater severity. Facilities identify message origin categories rather than replacing severity.'),
  q('4.5', 'A logging threshold includes severity 4 and more severe messages. Which message is excluded?', 'Severity 6 informational', ['Severity 0 emergency', 'Severity 3 error', 'Severity 4 warning'], 'The threshold includes numerical severities 0 through 4. Informational is 6 and is less urgent, so it falls outside this threshold.'),
  q('4.6', 'Where should ip helper-address be configured for clients whose DHCP server is on another subnet?', 'On the Layer 3 interface receiving the client broadcasts', ['Only on the server-facing switch access port', 'On every host’s web browser', 'Only on the loopback used as OSPF router ID'], 'The relay must receive the client broadcast and forward it to the server. It also identifies the client subnet so the server can choose an appropriate scope.'),
  q('4.6', 'Which command lets an IOS routed interface request its own IPv4 address by DHCP?', 'ip address dhcp', ['ip helper-address dhcp', 'ip route dhcp 255.255.255.255', 'switchport trunk native vlan dhcp'], 'ip address dhcp makes the interface a DHCP client. A helper relays other clients’ requests and does not itself assign the interface a lease.'),
  q('4.7', 'What is the distinction between traffic classification and marking?', 'Classification identifies traffic categories; marking writes a value used to signal treatment', ['Classification encrypts data; marking supplies a DNS record', 'They both require every packet to be dropped', 'Marking alone guarantees bandwidth at every downstream device'], 'Classification groups traffic; marking can set fields such as DSCP. Downstream devices still need policies that honor those marks; a mark alone is not an end-to-end guarantee.'),
  q('4.7', 'A congested egress interface must choose which queued packets to transmit next. Which QoS function addresses this?', 'Queue scheduling', ['DNS recursion', 'ARP aging', 'Changing the subnet mask'], 'Queuing and scheduling determine service during contention. Classification and marking can help choose queues, but their presence alone does not specify how queues are serviced.'),
  q('4.7', 'Which comparison correctly distinguishes policing and shaping?', 'Policing can drop or remark excess traffic; shaping buffers it to regulate transmission', ['Shaping always drops every excess packet immediately', 'Policing must buffer all traffic indefinitely', 'Both are forms of IPv4 NAT'], 'Shaping smooths traffic by buffering and delaying transmission. Policing enforces a rate with actions such as dropping or remarking excess packets; neither is address translation.'),
  q('4.7', 'A priority queue for voice is configured. Why still evaluate admission, queue limits, and congestion?', 'QoS allocates finite resources and cannot create unlimited link capacity', ['A priority queue makes every packet lossless forever', 'Voice priority disables all routing decisions', 'Congestion is impossible once a DSCP field exists'], 'QoS manages scarcity rather than removing it. Poorly bounded or overloaded priority traffic can harm other traffic and may itself suffer loss; capacity and policy design still matter.'),
  q('4.8', 'Which configuration ingredients support a typical local-user IOS SSH setup?', 'Hostname/domain, RSA keys, local user, login local, and SSH permitted on VTY lines', ['Only transport input telnet', 'Only an NTP server address', 'Only a static ARP entry for the client'], 'SSH needs server key material and an authentication policy along with reachable management addressing. login local selects the local user database; permitting only Telnet does not enable SSH.'),
  q('4.8', 'SSH is enabled, but the client cannot reach the management address. What should be checked before repeatedly regenerating keys?', 'Management routing, interface state, and access policy', ['The WLAN SSID on an unrelated laptop', 'The device’s VTY authentication settings as the only possible cause', 'The absence of a ping reply proves the RSA key is invalid'], 'Transport reachability and ACL/VTY policy can prevent connection before authentication. Key regeneration does not repair a missing route or denied management path.', '', 'Troubleshoot'),
  q('4.9', 'Which comparison of TFTP and FTP is accurate?', 'TFTP commonly uses UDP and has no built-in user authentication; FTP uses TCP and separate control/data connections', ['Both are inherently encrypted by default', 'FTP has no control connection', 'TFTP provides SSH key authentication'], 'TFTP is a simple file-transfer protocol without built-in authentication. Ordinary FTP is not encrypted and uses TCP control plus data connections; use an appropriate secure alternative when required.'),
  q('4.9', 'A router can reach a TFTP server but a configuration upload still fails. Which factor should be checked?', 'Server file permissions/path and whether the transfer traffic is allowed', ['Assume successful ping proves file transfer works', 'Assume only the NTP synchronization state controls TFTP permissions', 'Replace the TFTP server with an FTP client without testing the transfer path'], 'Ping tests ICMP reachability, not the TFTP transfer itself. Permissions, filename handling, server operation, and UDP transfer filtering can still cause failure.', '', 'Troubleshoot')
];
