<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TCP.Transport.Kestrel</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TCP.Transport.Kestrel.Tests" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../TCP.Core/TCP.Core.csproj" />
    <ProjectReference Include="../TCP.Networking.Pcap/TCP.Networking.Pcap.csproj" />
  </ItemGroup>
</Project>
